steps: 
# Build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/prak-tcc-d/frontend", "."]

# Push the container image to Container Registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/prak-tcc-d/frontend"]

# Deploy the container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - "run"
  - "deploy"
  - "frontend"
  - "--image"
  - "gcr.io/prak-tcc-d/frontend"
  - "--platform"
  - "managed"
  - "--region"
  - "us-central1"
  - "--allow-unauthenticated"
